[versions]
browser = "1.8.0"
compileSdk = "35"
ktorClientMock = "3.0.3"
lottieCompose = "6.7.1"
minSdk = "26"

accompanistPermissions = "0.37.0"
agp = "8.9.2"
apache-compress = "1.27.1"
apache-compress-xz = "1.10"
barcodeScanning = "17.3.0"
bcprovJdk15on = "1.70"
biometric = "1.1.0"
camera = "1.4.2"
coil = "2.7.0"
core = "3.5.3"
coreKtx = "1.16.0"
work = "2.10.1"
coreSplashscreen = "1.0.1"
datetime = "0.6.1"
espresso = "3.6.1"
datastorePreferences = "1.1.4"
junitJupiter = "5.11.4"
mockk = "1.13.16"
junit = "4.13.2"
junitVersion = "1.2.1"
kotlin = "2.1.20"
kotlinxCoroutinesCore = "1.10.1"
kotlinxProtobufGen = "0.1.0"
ktor = "3.0.3"
lifecycleRuntimeKtx = "2.8.7"
activityCompose = "1.10.1"
composeBom = "2025.09.00"
dagger = "2.56.1"
hilt = "1.2.0"
lifecycleViewmodelComposeVersion = "2.8.7"
navigationCompose = "2.8.9"
okhttp = "4.12.0"
room = "2.7.1"
sparkCore = "2.9.4"
annotation = "1.9.1"
walletCore = "4.3.22"
timber = "5.0.1"
ksp = "2.1.20-2.0.1"
appcompat = "1.7.0"
serialization = "1.8.0"
protobuf = "0.9.4"
rive = "10.4.5"
update = "2.1.0"
review = "2.0.2"
security = "1.0.0"
coreKtxVersion = "1.6.1"

[libraries]
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermissions" }
androidx-biometric = { group = "androidx.biometric", name = "biometric", version.ref = "biometric" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "browser" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-work = { group = "androidx.work", name = "work-runtime", version.ref = "work" }
androidx-work-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "work" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "coreSplashscreen" }
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastorePreferences" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt" }
androidx-material3-window = { group = "androidx.compose.material3", name = "material3-window-size-class-android" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
bcprov-jdk15on = { module = "org.bouncycastle:bcprov-jdk15on", version.ref = "bcprovJdk15on" }
core-zxing = { module = "com.google.zxing:core", version.ref = "core" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "dagger" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "dagger" }
hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "dagger" }
hilt-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hilt" }
hilt-common = { group = "androidx.hilt", name = "hilt-common", version.ref = "hilt" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junitJupiter" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesCore" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
androidx-security = { module = "androidx.security:security-crypto", version.ref = "security" }

apache-compress = { module = "org.apache.commons:commons-compress", version.ref = "apache-compress" }
apache-compress-xz = { module = "org.tukaani:xz", version.ref = "apache-compress-xz" }

kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-protobuf", version.ref = "serialization" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "datetime" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-camera-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "camera" }
androidx-camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "camera" }
androidx-camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "camera" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
androidx-espresso-intents = { group = "androidx.test.espresso", name = "espresso-intents", version.ref = "espresso" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-test-core-ktx = { group = "androidx.test", name = "core-ktx", version.ref = "coreKtxVersion" }
androidx-test-runner = { group = "androidx.test", name = "runner", version = "1.7.0" }
androidx-test-rules = { group = "androidx.test", name = "rules", version = "1.7.0" }
coil = { module = "io.coil-kt:coil-compose", version.ref = "coil" }

ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktorClientMock" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelComposeVersion" }
lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottieCompose" }
mlkit-barcode = { module = "com.google.mlkit:barcode-scanning", version.ref = "barcodeScanning" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
spark-core = { module = "com.sparkjava:spark-core", version.ref = "sparkCore" }
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
wallet-core = { module = "com.trustwallet:wallet-core", version.ref = "walletCore" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-serialization-kotlinx = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }

rive = { module = "app.rive:rive-android", version.ref = "rive" }
play-update = { module = "com.google.android.play:app-update", version.ref = "update" }
play-review = { module = "com.google.android.play:review", version.ref = "review" }
androidx-hilt-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "hilt" }


[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
daggerHiltAndroid = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
protobuf = { id = "com.google.protobuf", version.ref = "protobuf" }
